Nx.Notes:AddonNote("Candy Buckets - Alliance","Refuge Point",4,16,40,49)
Nx.Notes:AddonNote("Candy Buckets - Alliance","Dragon's Mouth",4,17,21,56)
Nx.Notes:AddonNote("Candy Buckets - Alliance","Fuselight",4,17,66,36)
Nx.Notes:AddonNote("Candy Buckets - Alliance","Surwich",4,19,45,88)
Nx.Notes:AddonNote("Candy Buckets - Alliance","Nethergarde Keep",4,19,61,14)
